# Generated by Django 4.2.3 on 2024-02-20 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('country', models.CharField(max_length=255, verbose_name='страна')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='номер дома')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='уровень в иерархии')),
            ],
            options={
                'verbose_name': 'индивидуальный предприниматель',
                'verbose_name_plural': 'индивидуальные предприниматели',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('country', models.CharField(max_length=255, verbose_name='страна')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='номер дома')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)], verbose_name='уровень в иерархии')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('model', models.CharField(max_length=255, verbose_name='модель')),
                ('release_date', models.DateField(verbose_name='дата выхода на рынок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('entrepreneurs', models.ManyToManyField(blank=True, to='electronics_network.individualentrepreneur', verbose_name='предприниматели')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.manufacturer', verbose_name='производитель')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('country', models.CharField(max_length=255, verbose_name='страна')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='номер дома')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='уровень в иерархии')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.manufacturer', verbose_name='производитель')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('retail_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.retailnetwork', verbose_name='розничная сеть')),
            ],
            options={
                'verbose_name': 'розничная сеть',
                'verbose_name_plural': 'розничные сети',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='долг')),
                ('buyer_individual_entrepreneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_individual_entrepreneur', to='electronics_network.individualentrepreneur', verbose_name='покупатель-индивидуальный предприниматель')),
                ('buyer_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_manufacturer', to='electronics_network.manufacturer', verbose_name='покупатель-производитель')),
                ('buyer_retail_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_retail_network', to='electronics_network.retailnetwork', verbose_name='покупатель-розничная сеть')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='electronics_network.product', verbose_name='продукт')),
                ('seller_individual_entrepreneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_individual_entrepreneur', to='electronics_network.individualentrepreneur', verbose_name='продавец-индивидуальный предприниматель')),
                ('seller_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_manufacturer', to='electronics_network.manufacturer', verbose_name='продавец-производитель')),
                ('seller_retail_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_retail_network', to='electronics_network.retailnetwork', verbose_name='продавец-розничная сеть')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='retailers',
            field=models.ManyToManyField(blank=True, to='electronics_network.retailnetwork', verbose_name='розничные сети'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.manufacturer', verbose_name='производитель'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='retail_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronics_network.retailnetwork', verbose_name='розничная сеть'),
        ),
    ]
