# Generated by Django 4.2.3 on 2024-02-22 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_network', '0002_alter_manufacturer_level_alter_retailnetwork_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='level',
            field=models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='level',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
